
spring:
  profiles: default, local
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect


---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://myDb.eu-west-1.rds.amazonaws.com:3306/conversationDB
    username: admin
    password: admin

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
